version: '3.8'


services:
  web:
    build: ./server
    depends_on:
     - db
    command: /app/run_server.sh
    volumes:
      - static_data:/app/static
      - media_data:/app/media
      - token_data:/app/token
    expose:
      - 8000
    env_file:
      - ./server/.env

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=auction
      - POSTGRES_PASSWORD=auction
      - POSTGRES_DB=auction_db

  nginx:
    build: ./nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - static_data:/var/www/html/static/
      - media_data:/var/www/html/media/
  network:
    build: ./network
    command: /app/network/create_tokens.sh
    ports:
      - "8545:8545"
    env_file:
      - ./network/.env
    volumes:
      - token_data:/app/network/build/contract

volumes:
  postgres_data:
  static_data:
  media_data:
  token_data:

