version: '3.8'


services:
  web:
    build: .
    depends_on:
     - db
    command: /app/run_server.sh
    expose:
      - 8000
    env_file:
      - ./.env

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=auction
      - POSTGRES_PASSWORD=auction
      - POSTGRES_DB=auction_db

  nginx:
    build: ./nginx
    depends_on:
      - web
    ports:
      - "80:80"

volumes:
  postgres_data: