version: '3.8'


services:
  web:
    build: ./server
    depends_on:
     - db
    command: /app/run_server.sh
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    expose:
      - 8000
    env_file:
      - ./server/.env

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=auction
      - POSTGRES_PASSWORD=auction
      - POSTGRES_DB=auction_db

  nginx:
    build: ./nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - static_data:/var/www/html/static/
      - media_data:/var/www/html/media/

volumes:
  postgres_data:
  static_data:
  media_data: